// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohgknbvklolynubikgds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oZ2tuYnZrbG9seW51YmlrZ2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzEyNDUsImV4cCI6MjA2MjY0NzI0NX0.k3kVznUKyL2HT0Y08mZMLFevnEvWJNKTuK4oVqMPeAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);